<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_100</name>
   <tag></tag>
   <elementGuidId>0ddb5767-4893-4db3-a484-df552478932a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Alokasi'])[1]/following::div[16]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-popup__container value editable ng-star-inserted</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  100
  %
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mli-typography-3 mli-light-theme app-container&quot;]/body[@class=&quot;mli-typography-3 mli-light-theme app-container&quot;]/app-root[1]/mli-mcbl-theme[@class=&quot;mli-typography-3 mli-light-theme app-container&quot;]/div[@class=&quot;main-body&quot;]/app-content-shell[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;nav mat-drawer-container mat-sidenav-container&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content ng-star-inserted&quot;]/section[1]/main[@class=&quot;main&quot;]/app-plan-setting[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;plan-setting propose-page router-content&quot;]/div[@class=&quot;plan-setting-content&quot;]/div[@class=&quot;protection-detail&quot;]/div[@class=&quot;right-content&quot;]/div[@class=&quot;main-content&quot;]/app-base-plan-detail-mission[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;base-plan-detail-mission plan-setting-page ng-pristine ng-touched ng-valid&quot;]/div[@class=&quot;scroll-area&quot;]/div[@class=&quot;common-setting&quot;]/div[@class=&quot;error-container&quot;]/div[@class=&quot;form-row&quot;]/app-fund-investment[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;fund-investment&quot;]/div[@class=&quot;fund-chart&quot;]/div[@class=&quot;fund-info&quot;]/div[@class=&quot;allocation&quot;]/div[2]/div[@class=&quot;allocation-value&quot;]/app-input-popup[@class=&quot;value&quot;]/div[@class=&quot;input-popup__container value editable ng-star-inserted&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alokasi'])[1]/following::div[16]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/app-input-popup/div</value>
   </webElementXpaths>
</WebElementEntity>
