<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uang Pertanggungan_controls__input</name>
   <tag></tag>
   <elementGuidId>eea80738-756a-4ad7-8420-ed7414320210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>controls__input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-number-pad[@class=&quot;ng-star-inserted&quot;]/div[1]/div[@class=&quot;number-pad&quot;]/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;input-popup__content topup-popup-content active&quot;]/div[@class=&quot;controls flex right&quot;]/div[@class=&quot;controls__container&quot;]/input[@class=&quot;controls__input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-number-pad/div/div/div[2]/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
